---
- name: Restart Xray VPN
  hosts: xray_nodes
  become: true
  pre_tasks:
    - name: Wait for SSH access
      ansible.builtin.wait_for_connection:
        delay: 2
        timeout: 30
        sleep: 2
  tasks:
    - name: Restart Xray Compose service
      community.docker.docker_compose_v2:
        project_src: /opt/xray
        files:
          - compose.yml
        services:
          - xray
        state: restarted
